/* eslint-disable prettier/prettier */
import { StyleSheet, Dimensions } from 'react-native';

const windowWidth = Dimensions.get('window');
export const styles = StyleSheet.create({
  view: {
    paddingBottom: 10,
    marginVertical: 20,
    marginHorizontal: 40,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    borderBottomColor: 'rgba(224, 224, 224,0.4)',
    borderBottomWidth: 1,
  },
  options: {
    fontSize: 35,
    fontFamily: 'Roboto-Bold',
    color: 'grey',
  },
  options2: {
    fontSize: 35,
    fontFamily: 'Roboto-Bold',
    color: 'black',
  },
  divider: {
    display: 'flex',
    flexDirection: 'column',
    borderLeftWidth: 2,
    marginTop: 10,
    marginLeft: 20,
    marginRight: 20,
    height: 30,
    justifyContent: 'center',
    borderLeftColor: 'rgba(92, 168, 224, 1)',
  },
  swipesGestureContainer: {
    height: '100%',
    width: '100%',
    backgroundColor: 'transparent',
    alignItems: 'center',
  },
  emptyText: {
    color: 'rgba(92, 168, 224, 1)',
    fontSize: 20,
    justifyContent: 'flex-start',
  },
  fab: {
    position: 'absolute',
    margin: 16,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(92, 168, 224, 1)',
  },
  listElement: {
    height: 70,
    width: windowWidth.width * 0.9,
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: 5,
    elevation: 2,
    borderRadius: 50,
    paddingLeft: 10,
    paddingRight: 10,
  },
  listText: {
    fontWeight: 'bold',
    color: 'black',
    fontSize: 20,
    width: '85%',
  },
  modalContent: {
    height: windowWidth.height * 0.65,
    width: '75%',
    backgroundColor: 'white',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignSelf: 'center',
    marginTop: '36%',
    elevation: 10,
    padding: 20,
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    padding: 20,
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalTitle: {
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 18,
    fontFamily: 'Roboto-Bold',

  },
  textFieldContainer: {
    display: 'flex',
    flexDirection: 'column',
    height: 100,
    width: '100%',
    alignItems: 'center',
    marginVertical: 15,
  },
  textinput: {
    width: '100%',
    backgroundColor: 'transparent',
    height: 50,
    fontFamily: 'Roboto-Bold',

  },
  actionsButton: {
    position: 'absolute',
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginBottom: 25,
    bottom: 0,
  },
  buttonsStyle: {
    color: 'rgba(92, 168, 224, 1)',
    fontFamily: 'Roboto-Medium',
    marginLeft: 20,

  },
  imagePicker: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginVertical: 20,
  },
  modalTitleInfo: {
    textAlign: 'center',
    fontSize: 38,
    color: 'rgba(92, 168, 224, 1)',
    fontFamily: 'Roboto-Medium',
  },
  scrollView: {
    height: windowWidth.height * 0.65,
    width: '75%',
    backgroundColor: 'white',
    display: 'flex',
    flexDirection: 'column',
    alignSelf: 'center',
    marginVertical: '36%',
    elevation: 10,
    padding: 20,
  },
  modalContentInfo: {
    justifyContent: 'flex-start',
  },
  infoTitle: {
    fontSize: 33,
    fontWeight: '600',
    width: '100%',
  },
  infoContnet: {
    textAlign: 'left',
    fontSize: 20,
    fontWeight: '600',
    color: 'rgba(0,0,0,0.5)',
    marginLeft: 8,
  },
  dividerLine: {
    borderBottomColor: 'rgba(92, 168, 224, 1)',
    borderBottomWidth: 2,
  },
  img: {
    flex: 1,
    alignSelf: 'stretch',
    width: 250,
    height: 250,
  },
  displayActionButtons: {
    marginTop: 10,
    marginBottom: 35,
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: 50,
  },
  modalContentInfoImage: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  deleteButton: {
    margin: 'auto',
    backgroundColor: 'red',
    width: 100,
    height: 35,
    padding: 8,
  },
  deleteText: {
    color: 'white',
    fontFamily: 'Roboto-Medium',
    textAlign: 'center',
  },
  emptyImage: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: 100,
  },
  infoContentImage: {
    display: 'flex',
    alignSelf: 'center',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },

});
